name: Publish to Github Pages
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: bahmutov/npm-install@v1
    - name: yarn run build.ci
      uses: CultureHQ/actions-yarn@master
      with:
        args: run build.ci
    - run: mv www build
    - name: publish
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
