name: Publish to Github Pages
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: bahmutov/npm-install@v1

    - name: Cache .stencil
      uses: actions/cache@v2
      env:
        cache-name: cache-stencil
      with:
        path: .stencil
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}

    - name: yarn run build.ci
      uses: CultureHQ/actions-yarn@master
      with:
        args: run build.ci

    - run: mv www build

    - run: chmod 777 ./build
    - run: echo "developers.layers.education" > ./build/CNAME

    - name: publish
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
